//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacion
    {
        public string codigo { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public int capacidad { get; set; }
        public string region { get; set; }
    
        public virtual Region Region1 { get; set; }
    }
}
